# Generated by Django 6.0.4 on 2026-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_commande_adresse_livraison_commande_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="mode_recuperation",
            field=models.CharField(
                choices=[
                    ("retrait", "Retrait sur place"),
                    ("livraison", "Livraison à domicile"),
                ],
                default="retrait",
                max_length=20,
            ),
        ),
    ]
