# Generated by Django 6.0.4 on 2026-04-21 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_commande_mode_recuperation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentaire",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="commentaire",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commentaire",
            name="note",
            field=models.IntegerField(
                choices=[
                    (1, "1 étoile"),
                    (2, "2 étoiles"),
                    (3, "3 étoiles"),
                    (4, "4 étoiles"),
                    (5, "5 étoiles"),
                ],
                default=5,
            ),
        ),
    ]
